#!/usr/bin/env ruby

require 'fileutils'

puts 'Uninstalling node modules...'
FileUtils.rm_r 'node_modules', :force => true

puts 'Removing third party libraries...'
FileUtils.rm_r 'public/javascripts/closure', :force => true
FileUtils.rm 'public/javascripts/jquery.tmpl.min.js', :force => true
FileUtils.rm 'public/stylesheets/bootstrap.min.css', :force => true
FileUtils.rm 'public/stylesheets/bootstrap-responsive.min.css', :force => true

puts 'Done.'
